//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLy
{
    using System;
    using System.Collections.Generic;
    
    public partial class NVIEN
    {
        public string MANV { get; set; }
        public string HOTEN { get; set; }
        public string DIACHI { get; set; }
        public Nullable<System.DateTime> NGSINH { get; set; }
        public Nullable<int> DIENTHOAI { get; set; }
        public string BANGCAP { get; set; }
        public string BOPHAN { get; set; }
        public string CHUCVU { get; set; }
    }
}
